### ISSUE TITLE
[3.2.X] Bug: Rate Questions - New (?) syntax for rate values is not usable (Not a bug, please improve the docs)

### ISSUE THREAD

**Issue by danowar2k** [PoetOS/moodle-mod_questionnaire#107]
From https://docs.moodle.org/32/en/Editing_Questionnaire_questions#Possible_answers_2

"Please note that in former versions of Questionnaire the separator between "short label" and "options text" used to be the equal sign (=). In Questionnaire 2.5 and later, please use two colons (::) as a separator. "

When using the mentioned new syntax with the two colons, the question using the new syntax is displayed incorrectly (multiple scales, one per value, instead of just one scale)

**Comment by mchurchward** [comment]
Could you provide an exact set of data you entered to see this problem, and the version you are seeing it on please?
Thanks.

**Comment by danowar2k** [comment]
Ok, this is not a bug. It's just the questionnaire documentation at moodle.org which is lacking (for me). I was totally confused by the "possible answers" and the examples. Could you please edit the docs so that the "Rate" section first explains the general syntax used for the "Possible answers" form field (both types of syntax) and change the examples to make them less confusing? I think the main part is calling "subquestions" "possible answers", which is a definition better used for Radio Button questions.

**Comment by danowar2k** [comment]
Will open a new one if problem persists.
