### ISSUE TITLE
[3.2.X] [3.3.1] FR: Please split the form field containing question choices and subquestion labels into two form fields

### ISSUE THREAD

**Issue by danowar2k** [PoetOS/moodle-mod_questionnaire#110]
It would be more logical to have separate form fields for "question choices" and "subquestion labels" (the "possible answer" part in the form field), I think

**Comment by danowar2k** [comment]
Also, I would propose splitting the subquestion labels for a question and the question choices at the table end.

**Comment by danowar2k** [comment]
I compared 3.2.4 to 3.3.1 . The above issue exists there, too (updated title accordingly)

**Comment by mchurchward** [comment]
Release 3.7.0 changes the UI for this. Closing this issue.
