### ISSUE TITLE
[3.2.X] [3.3.1] Rate Choice syntax not consistently validated

### ISSUE THREAD

**Issue by danowar2k** [PoetOS/moodle-mod_questionnaire#111]
Questionnaire 3.2.4. Sometimes two digits, sometimes three digits make a choice.

Sources:
rate.php, line 538:
> if (preg_match("/^[0-9]{1,3}=/", $choice)) {

base.php, line 902:
> $r = preg_match_all("/^(\d{1,2})(=.*)$/", $newchoices[$nidx], $matches);

Proposed solution: Define one or more global regular expression constants. Use brackets in these to define capturing groups. Use capturing groups when necessary.

**Comment by danowar2k** [comment]
I compared 3.2.4 to 3.3.1 . The above issue exists there, too (updated title accordingly)

**Comment by mchurchward** [comment]
This code has been substantially refactored in the MOODLE_37_STABLE branch. Closing this issue.
