### ISSUE TITLE
what is the purpose of the sec required param in print.php ?

### ISSUE THREAD

**Issue by Tazoeur** [PoetOS/moodle-mod_questionnaire#114]
Hi there,
I was wondering what was the purpose of the 'sec' required param that you can see in print.php

It seems to do nothing except prevent access to url without it, the only use of it beeing adding this parameter to $url...

I've seen this trying to create a moodle url and I didn't know what value I should give to the sec parameter.

Have a nice day,
Guillaume

**Comment by mchurchward** [comment]
Fix provided in https://github.com/PoetOS/moodle-mod_questionnaire/pull/112
