### ISSUE TITLE
Improve the completion page "continue" link

### ISSUE THREAD

**Issue by mchurchward** [PoetOS/moodle-mod_questionnaire#118]
The link should be a button like the other UI links. See https://moodle.org/mod/forum/discuss.php?d=361634

**Comment by mchurchward** [comment]
Fixed in latest 3.7.

**Comment by adpe** [comment]
Hi @mchurchward 

Did you mean this https://github.com/PoetOS/moodle-mod_questionnaire/pull/240 merge?

As I see on the viewpage and the completionpage are still old. Therefore, we should reopen this issue.

Greets,
Adrian

**Comment by mchurchward** [comment]
No. It was in this [commit](https://github.com/PoetOS/moodle-mod_questionnaire/commit/b923f521f7bba7d78e190f5131a8854cc1b9f314)
