### ISSUE TITLE
Add idnumber field option in export CSV 

### ISSUE THREAD

**Issue by papillon326** [PoetOS/moodle-mod_questionnaire#120]

**Comment by adpe** [comment]
Hi @papillon326 

It should be now possible for you to use this id number. There are now two new exportoptions!

@mchurchward: I think this issue can be closed?

HTH, Adrian

**Comment by mchurchward** [comment]
I had pulled this change in, but I now realize it was redundant. Adding the database 'id' field for the user has been part of the export for a long time. It is listed as the "ID" option.
I am going to back this change out.
Or perhaps, this was meant to be the 'idnumber' field of the user?

**Comment by papillon326** [comment]
Yes, 'idnumber ' mean 'student idnumber' not 'course module id'.
