### ISSUE TITLE
Tests failure because of hardcoded year

### ISSUE THREAD

**Issue by peikk0** [PoetOS/moodle-mod_questionnaire#122]
Hi,

the year 2017 is hardcoded in `expected_output()` from `tests/csvexport_test.php`, but in `generate_response()` from `tests/generator/lib.php` the year is actually the current one (`$date = mktime(0, 0, 0, 12, 28, date('Y'));`), making the tests fail now that we are in 2018. I guess we should use `date('Y')` in the expected output.

Cheers,
Pierre

**Comment by mchurchward** [comment]
Yah. I saw that too. If you can provide a patch as a pull request, that would be great.

**Comment by mchurchward** [comment]
Commit https://github.com/PoetOS/moodle-mod_questionnaire/commit/f604e08f41bea80c54cb9787f0b1e040cd9f1442 included a fix for this problem.
