### ISSUE TITLE
Mobile support review my code

### ISSUE THREAD

**Issue by tigusigalpa** [PoetOS/moodle-mod_questionnaire#129]
Hi Mark!
I made some code for mobile integration for your plugin. Can you take a look?
https://github.com/tigusigalpa/moodle-mod_questionnaire/tree/mobileversion

Ionic backed code:
https://github.com/tigusigalpa/mod_questionnaire_mobile

I'm open for discuss

**Comment by mchurchward** [comment]
Hi Igor. Thanks for the effort, but it appears that Moodle is changing the way 3rd party plugins work with Moodle Mobile. See - https://tracker.moodle.org/browse/MOBILE-2333

**Comment by anatolyg7** [comment]
Mike,

new code is under way - will be ready soon.

**Comment by mchurchward** [comment]
Awesome. I'll look over that soon.

**Comment by tigusigalpa** [comment]
@mchurchward This is not a final version, some small issues are on the way (pagination for example)

**Comment by tigusigalpa** [comment]
Hi all!
The code of Moodle Mobile integration is done at my best. This was a hard challenge because a lot of limits Mustache, Angular, Ionic and the very first work about like tgis work, so a lot of learning as you go. Thanks to @dpalou and @marcusgreen for your help and advices and of course to @mchurchward as a creator of this great plugin!
commit here https://github.com/tigusigalpa/moodle-mod_questionnaire/commit/02950d3acbd944eebd333bd25fe28d02e05fcad5
**What wasnt included and for the future:**
- Included **ONLY** these questions types: **select, bool, radio, checkbox, text, essay, rank**
- I did not use some plugin-based functions that i has to, because it based on **$_POST** variables and for some another reason, so maybe in future we have to make a work about compare it (for example function to submit survey)

**Bugs and another moments to work for Moodle Mobile DEV Team**
- **Textarea/input** switching to disabled if add **formControlName** in form to make validation, so this is a bug i think, so i use core-rich-text-editor. _I found a code with in Moodle Mobile Angular but lost it for now and cant refresh it)_
- I dont uderstand how to return after submitting some data **from PHP to JS**, maybe this is not exists for now but will be useful
- If use a **Angular model** and collect form data to **CONTENT_OTHERDATA** by **CoreUtilsProvider.objectToArrayOfObjects** - all data goes to args. I think the cool way will be exclude array with **Moodle-backed key "warnings"** to handle the ones outside and dont have WS errors
- Moodle Mobile has an attribute for submit button named **goBackOnSuccess** (https://docs.moodle.org/dev/Mobile_support_for_plugins#core-site-plugins-call-ws) but i dont understand what means "**Success**" at this case?

**Comment by dpalou** [comment]
Hi Igor!

I took a quick look at the code and I didn't see anything wrong, good job!

Regarding the last points:

- I'll take a look at the textarea issue. In the app we usually use ngModel with ion-textarea, and I see that in one place we also use _ngControl="control"_, but we don't have any case with formControlName.
- I think this could be related to the last point. If you want to go back to the previous view (like when the user clicks the Back button) when a WS call is "successful" you can use the **goBackOnSuccess** input. A "successful" WS call means that it is a successful HTTP request and it doesn't return any exception. You can also go back manually in your JS code, using _this.NavController.pop();_. In v3.5.2 we added some outputs to be able to run your custom JS code when the WS call is done, I documented them in the wiki (onSuccess, onError, onDone).
- I'm not sure if I understand this point. Do you want to exclude some of the data you collected from the form? Please notice that you can always use _(click)="myFunction()"_ to implement your own code, that way you can do whatever you want with the data.
- Please see the second point :)

Cheers,
Dani

**Comment by tigusigalpa** [comment]
Hi, Dani!
Thanks a lot for reply and good words about the job!
- Yes, this is very big problem with **ion-textarea/ion-input**
- Yes, i see that "**success**" means response without exceptions, but i think will be great to make some flag for success in response to understand from JS the reason or data what goes wrong on request (**PHP->JS**). Just idea about server validation **from PHP to Angular/JS**.
- Yes, i saw docs about **onSuccess, onUpdate etc**, but for now i dont understand how to use it, do you have some examples?
- is _(click)_ function has access to **CONTENT_OTHERDATA** from the form?

**Comment by tigusigalpa** [comment]
- also i tried to return separated array from WS with success data and warnings (**\external_warnings** class) https://github.com/tigusigalpa/moodle-mod_questionnaire/commit/02950d3acbd944eebd333bd25fe28d02e05fcad5#diff-f232daf9e853b92201e86b2262bc9acaR115, but i cant because warnings are multidimensional array and i used **CoreUtilsProvider.objectToArrayOfObjects** (to convert **name=>value**) and returned **args** array contains name (or value) with content like **warnings[0][key]** and this is WS error about **PARAM_ALPHANUM** cant contains data like this. So idea is to separate/exclude/handle data from server to Angular. My English is not perfect but i hope i described my idea clearly.

**Comment by dpalou** [comment]
Hi Igor,

Angular components have inputs and outputs.
Inputs are used to pass data to components, and they use square brackets []; for example, [formGroup] or [params].
Outputs are used to return some data from the component to the outside, or to notify something has happened inside the component, and they use parenthesis (). In this case you need to specify a **function** to call when the component decides to call the output. For example, (click)="doSomething()" or (onSuccess)="myFunction($event)".

So you'd have to implement that javascript function and assign it to the component:

```
this.myFunction = function(result) {
...
}
```
In this function you have access to the same variables as you did in the rest of JS code, so you have access to CONTENT_OTHERDATA and everything else. You see that the (onSuccess) has a $event in it, you need to do that to indicate that you want the function to receive the data that the component is sending (in onSuccess, it's the result of the WS call).

Regarding the warnings and so, the app considers warnings as a success. If you want to treat them you can do so using the "onSuccess" output, since it receives the result of the WS call.If Moodle is giving you an error when you return them, maybe you can treat the array in the WS before returning it?

If you want we can talk about this in private so we don't post so much in this issue :)

**Comment by mchurchward** [comment]
Hi Igor.
I'm in the process of reviewing your code.
In lib.php, in the new function save_questionnaire_data (line 791), you have $CFG declared as a global with the comment 'Do not delete $CFG!!!'. But $CFG doesn't appear to be used within that function. Why is it there?

**Comment by danmarsden** [comment]
it will be due to this line:
https://github.com/tigusigalpa/moodle-mod_questionnaire/blob/MOODLE_35_MOBILE/questionnaire.class.php#L26

- which probably shouldn't be there?

**Comment by tigusigalpa** [comment]
Hi, Mike!
Dan Marsen @danmarsden is probably right, i had some mistake at console and hardly commented it, honestly i didnt remember all details.

**Comment by mchurchward** [comment]
@danmarsden the line you referenced is "require_once($CFG->dirroot.'/mod/questionnaire/locallib.php');". That line needs to be there as many of the functions in the class call functions from that library file. (some day, refactoring may kill the need for that...)
In any case, I don't see why that would mean including a $CFG that is not used. I'm going to assume that its old code and can be removed.

**Comment by mchurchward** [comment]
@tigusigalpa I use the Travis CI plugins to check the code and ensure that it meets the coding requirements of Moodle. You added two new templates. They require example contexts in the header to be validated. Can you add these if possible? If not, I will try to go through the template and figure it out.

**Comment by mchurchward** [comment]
@tigusigalpa I am trying to test this locally with the Moodle Desktop app on MacOS. Whenever I click a questionnaire, I get the error "Error reading database."
Any ideas?

**Comment by tigusigalpa** [comment]
@mchurchward hmm, the best way is to install **ionic+moodlemoblie**:
1. install nodejs (im sure you have it)
2. Download Chromium https://download-chromium.appspot.com/
3. go to your working mobile folder
4. `npm install -g cordova ionic`
5. `npm install -g gulp`
6. `git clone https://github.com/moodlehq/moodlemobile2.git moodlemobiledirectory`
7. `cd moodlemobiledirectory`
8. `npm run setup`
9. `npm install`
10. `cordova prepare`
11. `npm link gulp`
12. `gulp`
13. `ionic serve --browser **PATH_TO_CHROMIUM** --allow-file-access-from-files --disable-web-security --user-data-dir`
14. Wait until webpack build the project (in my case 2-3 mins), Chromium will start automatically, So you will have an access to console to debug.
Also i see you did an update for MOODLE_35_STABLE after this commit, maybe this case?

**Comment by mchurchward** [comment]
I'll try those steps. I think I have prior, but who knows.
I'm trying to run your version before  I made any changes at https://github.com/tigusigalpa/moodle-mod_questionnaire/commit/bc1a3b32a376871db82a31b11363aaad014e69cd
This gives me the database error message in the desktop app.

**Comment by mchurchward** [comment]
So, in the moodlemobile directory, when I run "npm run setup", it exits with the error:

Current working directory is not a Cordova-based project.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moodlemobile@3.5.1 setup: `npm install && cordova prepare && gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the moodlemobile@3.5.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by danmarsden** [comment]
Mike - you shouldn't need to build the app itself - you should be able to use https://mobileapp.moodledemo.net/ (in chrome) and then connect to your local machine - I've also used the standard mobile app on my local device to connect to a local dev machine over wifi and it works well too.

The issue with the global $CFG in the save_questionnaire_data is that @tigusigalpa is including the questionnaire class in the function, which will fail if you remove the global $CFG - in an ideal world.. the questionnaire class would be in the classes folder and you'd use auto class loading and the locallib file would be included already by the file trying to access the questionnaire stuff.

**Comment by mchurchward** [comment]
Hi Dan. I tried using the https://mobileapp.moodledemo.net/  with my local machine. But as far as I can tell, that does not help debug PHP code. Unless I'm missing something.

**Comment by marcusgreen** [comment]
If you have a machine where the php is debuggable (xdebug in the php config) and it is on the public facing web, you should be able to set up a breakpoint in php in your ide and then access it through https://mobileapp.moodledemo.net/

When it gets to the appropriate line in the PHP it should stop at the debug point. At least I think so, Dan can probably confirm.  So far as I am concerned npm is a nightmare of random unintelligable commands that unfortunately my living is dependent on. However you may find that Homebrew does a better job of installing these things than native npm.

**Comment by danmarsden** [comment]
I'm not sure that compiling your own app will help much with debugging. The browser console of the mobile app gives you a lot of help with errors that are occurring within the app, but php code debugging is really done on the "server" - rather than in the app from what I understood? (I could be wrong though)

When I've been working on adding support for the mobile app to the attendance plugin (using the new method) I found using mobileapp.moodledemo.net worked ok for me. (Although there was a decent learning curve :-) )

**Comment by marcusgreen** [comment]
Dan, are you advocating a world of var_dump($varname)

**Comment by danmarsden** [comment]
heh - I'd tend more towards using error_log with the mobile app :-)

the biggest pain I found with debugging the mobile app was the caching within the app - keep an eye on the browser console messages in chrome - it will tell you if the page has been fetched from the cache.

**Comment by mchurchward** [comment]
Well. I've tried monitoring the httpd error logs, and nothing appears there. Ideally, it would be good to get a stack trace pointing to where in the code the "Error reading from database" is coming from. I don't think I can do that with the mobile app without being able to turn in some sort of debugging mode?

**Comment by marcusgreen** [comment]
MIke, check out this call in classes/output/mobile
 $questionnaire = get_questionnaire_data($cmid, $USER->id);
You may have an error in there somewhere (bit of a wild guess based on doing an exit before and afterwards). If I exit before I get a different error message, if I exit after I get the error you are seeing.

**Comment by mchurchward** [comment]
I figured out the bug. It is a database field change between Igor's code and mine. I'll update to fix.

**Comment by tigusigalpa** [comment]
> I'm not sure that compiling your own app will help much with debugging. The browser console of the mobile app gives you a lot of help with errors that are occurring within the app, but php code debugging is really done on the "server" - rather than in the app from what I understood? (I could be wrong though)
> 
> When I've been working on adding support for the mobile app to the attendance plugin (using the new method) I found using mobileapp.moodledemo.net worked ok for me. (Although there was a decent learning curve :-) )

@danmarsden No, its the best way to debug via Netrwork Tab (near Console Tab) like in native Chrome on server.php file, it will show php errors.
You have to use MOODLE_35_STABLE branch to test: https://github.com/PoetOS/moodle-mod_questionnaire/tree/MOODLE_35_STABLE
@mchurchward As i see, you found the bug, probably you've been tested on master branch

**Comment by mchurchward** [comment]
I figured out the bug. It is a database field change between Igor's code and mine. I'll update to fix.

**Comment by mchurchward** [comment]
Hi @tigusigalpa. I really appreciate all of the effort you put into this. As I'm going through it, I'm running into some problems. It doesn't seem that the mobile handles "save" and "submit" any differently. A questionnaire can allow "saving", which means that the current state of the response is saved without actually being submitted. When the user comes back, they can renew the response where they left off. "Submitting" on the other hand is permanent. Once submitted, the response cannot be changed.
Also, questionnaires can allow multiple submissions from a user. I think the mobile code fails if that has occurred.
I'm going to try and see if I can refactor some of the new PHP code you provided into the question classes. I think that will help make this easier to continue.

**Comment by mchurchward** [comment]
Hi Igor. Sorry, I wasn't complaining; just establishing what it is you have accomplished so far. What you've done is a great start and will help determine what we can do.
I think the next big steps will be determining what functions need to exist for both mobile and web. We want to make sure we have to write the page/question/response handling code only once. I'm giving myself a crash course in what you've done and how it works now.
Does what you've done so far handle question dependencies and feedback? (I'm thinking no). I'm also guessing the way questionnaire works, this will be really difficult to get it to run offline as a download...
I'm going to split this work out as a new Github project and hope you will help continue it.

**Comment by marcusgreen** [comment]
Hi Igor, just want to second what Mike has said, your progress is very impressive. I did a presentation for the developers meeting last week about developing for mobile. It is all about question types so it might not be relevant to your work, but here is a link
https://moodle.zoom.us/recording/play/mtX7qcu_G9HnEIxfEuxjMVCX7PmZqAG7128XnAWUkLfvVLusBS07tIyJ5U-pv1Sm?continueMode=true

**Comment by anatolyg7** [comment]
> Does what you've done so far handle question dependencies and feedback? (I'm thinking no). I'm also guessing the way questionnaire works, this will be really difficult to get it to run offline as a download...
It does handle dependencies (at least simple dependencies like showing certain pages after choosing a variant). As for feedback - probably no, since it is rarely used in our environment.

**Comment by mchurchward** [comment]
Hi. I'm going to close this issue now and continue the work in the 'Mobile App' project here. I made some fixes in issue 156 that allowed me to submit a questionnaire in the mobile app. This code is now in the MOODLE-MOBILE_35_BETA branch which we will use as the base for the continued work. We can create further issues in the Mobile App project for this.
Thanks for getting this started!

**Comment by mchurchward** [comment]
By the way, you can access the Mobile project board here - https://github.com/PoetOS/moodle-mod_questionnaire/projects/1

**Comment by tigusigalpa** [comment]
I saw the project. Is the refactor issue is neccessary for production?

**Comment by mchurchward** [comment]
I think some does, just to reduce code duplication. I'm working on that now. I may need to ask you some questions about the data you're extracting.

**Comment by tigusigalpa** [comment]
Yes, i understand, but as i wrote before, i didnt refactor it because of im not 100% owner of the code and you know its better, also your current code is backed to web features like superglobal variables $_POST and sessions. Also, to be honest - this is a huge work with lot of tests work))

**Comment by mchurchward** [comment]
No worries. I'll take what you provided and do some initial refactoring to help it out. I have been working over time to get rid of dependencies on superglobals. I welcome any input you have on where they are still used.
As far as I know, $_POST is only used in the unit tests and in the graphing javascript library. Any others?
