### ISSUE TITLE
Check Boxes type: Multiple-choice multiple-answer summary shows wrong(?) averages

### ISSUE THREAD

**Issue by Dagefoerde** [PoetOS/moodle-mod_questionnaire#135]
The summary of questions using a Check Boxes question type displays averages which we think are incorrect / not useful for interpretation. See the screenshot for illustration:

![aggregation by responses](https://user-images.githubusercontent.com/432117/41036061-062e25b4-698f-11e8-8f6b-2a23e36a59d5.png)

For example, choice 2 has been selected by 61 out of 68 persons (about 90%). However, the average is displayed as 37%, i.e. 61 out of 166 responses(!).  I am not sure how this measure might be interpreted, so maybe it is not wrong per se.

**Expected behaviour:** 
I expect to see the ratio of the respondents who chose that option. This could either be in addition to the existing measure, or instead of it.

**Comment by Dagefoerde** [comment]
Ohh, and right after submitting I found a pull request that tackles exactly this:
https://github.com/PoetOS/moodle-mod_questionnaire/pull/131

Judging by its description it solves exactly my problem. Could it be merged? That would be great, thanks.

**Comment by mchurchward** [comment]
Making sure I understand the current behaviour. In the example, 166 people have responded to the questionnaire, but only 68 have answered that particular question. Is that correct? Given that, I think we should also add a line that shows the percentage of the respondents who answered the question (68/166). The final line looks like it was meant to do that, but isn't.

**Comment by Dagefoerde** [comment]
No, 166 responses to that particular question were recorded (it's the sum of the individual counts in the rightmost column), but every respondent was able to check an arbitrary number of answers, resulting in >= 1 responses per respondent. 68 is the number of respondents to the questionnaire.

**Comment by mchurchward** [comment]
I think it might be better to add a "Did not respond" line as well, and then have the totals reflect the number of responses per total respondents to the questionnaire, and the "Total" line show the percentage of respondents who responded to that question. Like this:
![screen shot 2018-07-04 at 11 06 11 am](https://user-images.githubusercontent.com/819054/42284509-b85ce486-7f7a-11e8-8773-7b503ec584f2.png)

**Comment by kyro46** [comment]
Infomation about the percentage of respondents is a good idea. But I think the "Did not respond"-Line is redundant if the "Total"-line already shows the reciprocal percentage, which should therefore not be named "Total" but "Answered by", to distinguish it from the percentages of the checkboxes.

Since this last line does not refer to the single checkboxes anymore, I'd suggest to change the"#ticks/#participants in this survey" (e.g. in the screenshot 23/28, which reads as "23 ticks given by 28 participants" from wich only 23 actually answered as seen by "Did not respond"), to only show "n=23" (answered by 23 persons).

**Comment by mchurchward** [comment]
You said:

> The percentages for the checkboxes should reflect the ratio of the persons who actually answered the question and not include skipped questions in the calculation.
If the "did not respond" line was excluded, then I think the above would make sense. I included the "did not respond" line so it was clear that there was a number of questionnaire respondents who did not answer the question, either by ignoring it or by not seeing it (in the case of a conditional branch).
I can see a need for both options. I'll put some more thought into it.

**Comment by mchurchward** [comment]
Okay. Looking at it again, I think your comments are correct. I've removed the "did not respond" line, changed the percentages to be based off the number of question responses and left the total line to be number of question responses over the number of questionnaire respondents.

![screen shot 2018-07-12 at 10 08 22 am](https://user-images.githubusercontent.com/819054/42638441-a466752c-85bb-11e8-94e0-7e6921e15950.png)

I also have created template files for the question display to make it easier to change in the future. You can see it on the MOODLE_35_LEIPZIGDEV branch.

**Comment by Dagefoerde** [comment]
These percentages look a lot more useful, thank you! :+1:

**Comment by mchurchward** [comment]
This has been dealt with in the latest commit and forthcoming release.
