### ISSUE TITLE
Upgrade to 3.4.1  breaks database schema droping 2 columns in questionnaire_question

### ISSUE THREAD

**Issue by xmontana** [PoetOS/moodle-mod_questionnaire#137]
Dear all,

We have testing to upgrade the plugin in Moodle 3.5+ (Build: 20180531) with php 7.0.

Our test upgrades the plugin from 3.3.3 (Build - 2018013100) (2017050103) to 3.4.1 (Build - 2018013100) (2017111102). After this we check the database schema with command:  admin/cli/check_database_schema.php

The script notify us that two the columns are missing:

```
-------------------------------------------------------------------------------
questionnaire_question
 * column 'dependquestion' is missing
 * column 'dependchoice' is missing
-------------------------------------------------------------------------------
```

We have try to do a fresh install of the version 3.4.1 of mod_questionnaire and the two columns are created. Te content of the 2 columns are filled with data before upgrade so the data is lost!

We have made multiple test upgrading from diferent version plugins, and the columns are droped with the 3.4.1 version.

Could you revise?

Thanks you very much

**Comment by xmontana** [comment]
I have reviewed the update BBDD process and I see that the 2 drooped columns are migrated to new table (questionnaire_dependency), and all data is migrated to this new table.

`if ($oldversion < 2017111101) {`

**So the issue it's not as serious as I thought, the data is correctly migrated.** The issue is only in the schema definition, and fails in the moodle check.

**Comment by mchurchward** [comment]
Hi. This was fixed in the MOODLE_34_STABLE branch here - https://github.com/PoetOS/moodle-mod_questionnaire/commit/a74dba715b0b6582031241c70dcb37af7039becd
It was previously reported in the Moodle Tracker - https://tracker.moodle.org/browse/CONTRIB-7300.
The next releases of questionnaire will include these changes.
