### ISSUE TITLE
Make plugin compliant with Moodle GDPR

### ISSUE THREAD

**Issue by ilya-catalyst** [PoetOS/moodle-mod_questionnaire#138]
Since Moodle 3.4 all plugins should comply with GDPR https://docs.moodle.org/34/en/GDPR, https://docs.moodle.org/dev/Privacy_API. I can see branches for Moodle 3.4 and 3.5 but there are no metadata or request provider there, hence Moodle unit tests are failing

**Comment by mchurchward** [comment]
Yep. And it will. As soon as the work has been completed.

**Comment by mchurchward** [comment]
Latest release includes this work.
