### ISSUE TITLE
 PHP Warning:  A non-numeric value encountered in /mod/questionnaire/classes/response/rank.php on line 147

### ISSUE THREAD

**Issue by mgancarzdsi** [PoetOS/moodle-mod_questionnaire#145]
Hi all, we've updated to Moodle 3.5 and were using build 2018013100 of the questionnaire plugin. I'm updating to build 2018061900 but I don't think this issue will be fixed in that one as I don't see any code changes to the related code.

I'm seeing the apache httpd error log having a lot of these messages being reported:  PHP Warning:  A non-numeric value encountered in /mod/questionnaire/classes/response/rank.php on line 147

when a person clicks the "View all responses" button. ie: /mod/questionnaire/report.php?instance=2279&group=0

I can't find anything outright broken though.

**Comment by rezeau** [comment]
I'm having the same type of error with the latest version of Questionnaire (with Moodle full debugging ON).
Notice: A non well formed numeric value encountered in C:\xampp\htdocs\moodle\mod\questionnaire\classes\question\rate.php on line 384
 and also line 177.
I suggest a simple fix: 
In all those lines:
`        -

         if ($osgood) {
            if ($maxndlen < 4) {
                $width = '45%';
            } else if ($maxndlen < 13) {
                $width = '40%';
            } else {
                $width = '30%';
            }
            $nn = 100 - ($width * 2);
            $colwidth = ($nn / $this->length).'%';
            $textalign = 'right';
        } else if ($nocontent) {
            $width = '0%';
            $colwidth = (100 / $this->length).'%';
            $textalign = 'right';
        } else {
            $width = '59%';
            $colwidth = (40 / $this->length).'%';
            $textalign = 'left';
        }
`
replace e.g. `$width = '45%';` with `$width = '45';` i.e. remove the % character.

**Comment by davidpesce** [comment]
@rezeau how would this fix those errors?

**Comment by rezeau** [comment]
I gave the fix in my post: simply remove the % character from all the **width = '00%'** (00 being a number)

**Comment by davidpesce** [comment]
Yeah, I understand your comment/fix, but it doesn't fix the error that @mgancarzdsi posted. I tried it on the latest version of the plugin and Moodle 3.5+

**Comment by mgancarzdsi** [comment]
The "Non well formed numeric value" and "non-numeric value" error messages are for two similar, but different issues. https://wiki.php.net/rfc/invalid_strings_in_arithmetic The error I'm encountering is reportedly on line 147, not 177 and 384.

**Comment by davidpesce** [comment]
@mgancarzdsi - any chance you've been using questionnaire plugin since Moodle 1.9-2.x for this instance?

I'm running into the same problem and submitted another ticket with some more info here: #172 

I'm getting further errors when trying to download the responses to CSV. I ended up writing SQL queries to get the data I need, but noticed that in both of the questionnaires (that I'm having trouble with), there are null values for one of the questions (only part way through).

**Comment by mgancarzdsi** [comment]
@davidpesce Yes, I think there's a good chance of that. Some of the questionnaires have been duplicated and re-used for future courses since 2011, which was definitely Moodle 1.9/2.0 era.

**Comment by davidpesce** [comment]
Same here. My client is coming from 1.9+. I just did all the upgrade hops to get them up to v3.5 (upgrading questionnaire during each hop) and this is the only casualty (amazingly). Maybe @mchurchward has some ideas/thoughts as to why this could happen. I'm happy to dig further with some pointers on where/what to look for.

**Comment by mgancarzdsi** [comment]
Also now, that I've updated to the latest Questionnaire release, the error has shifted to line 129  "PHP Warning:  A non-numeric value encountered in /var/www/html/learning.desouzainstitute.com/mod/questionnaire/classes/response/rank.php on line 129"

which corresponds to: https://github.com/PoetOS/moodle-mod_questionnaire/blob/769c45d6be785d80db2d82773bc698e9f94154dd/classes/response/rank.php#L129

**Comment by mgancarzdsi** [comment]
Or rather:
https://github.com/PoetOS/moodle-mod_questionnaire/blob/769c45d6be785d80db2d82773bc698e9f94154dd/classes/response/rank.php#L118-L133

**Comment by davidpesce** [comment]
Yup, I'm using the latest build. I think the key to replicating this is to have very old versions of questionnaires in it. It doesn't seem to happen on any that are newly generated.

**Comment by mgancarzdsi** [comment]
Yep, on 3.5.3 (Build - 2018121000)

I've isolated a survey it happens on that I could share with you @mchurchward . How would you like me to send it?

Steps to reproduce would be:
1) Restore the questionnaire into a course
2) Fill it out
3) View all responses. 10+ Errors are generated when all responses are viewed, even with just 1 response being shown

**Comment by mchurchward** [comment]
Can you attach it to a comment here?

**Comment by mchurchward** [comment]
Thanks. This looks like the same problem as [issue 172](https://github.com/PoetOS/moodle-mod_questionnaire/issues/172). The commit in that issue should fix this. Closing.
