### ISSUE TITLE
Add new field to downloadoptions (csv export)

### ISSUE THREAD

**Issue by adpe** [PoetOS/moodle-mod_questionnaire#153]
Hello @mchurchward 

Would it be possible to add a new field to the downloadoptions? Maybe it would be great to add all available fields and let the user select which ones he wants.

At the moment the needed field is not available for us. We helped us out and added this field, but it's not in the official repository.

**Comment by mchurchward** [comment]
Is this the idnumber request?
I am going through all the pull requests provided over the next weeks, and I will be including them in the next release if they are complete.

**Comment by adpe** [comment]
No it's a different one. 

What I was thinking is, if you want add each downloadoption "hardcoded" to the `configmultiselect` or if there would be another solution with a textarea, where the fields wanted can be added/removed dynamically.

I'll post my solution based on issue #120 , and will be glad to hear from you.

**Comment by adpe** [comment]
Look @ pull request https://github.com/PoetOS/moodle-mod_questionnaire/pull/155

**Comment by adpe** [comment]
Thanks @mchurchward 

Therefore I'm closing this issue!
