### ISSUE TITLE
Deleting questions doesn't work

### ISSUE THREAD

**Issue by knarzhupe** [PoetOS/moodle-mod_questionnaire#154]
Deleting questions from a questionnaire fails at the point of deletion of answers with the follwing error:

`Error: Argument 2 passed to moodle_database::count_records() must be of the type array or null, boolean given, called in [dirroot]/mod/questionnaire/questions.php on line 108`

Looking into the code i found that this bracket seems wrongly placed:
```
@@ -105,7 +105,7 @@
         questionnaire_delete_responses($qid);

         // If no questions left in this questionnaire, remove all responses.
-        if ($DB->count_records('questionnaire_question', ['survey_id' => $sid, 'deleted' => 'n'] == 0) ) {
+        if ($DB->count_records('questionnaire_question', ['survey_id' => $sid, 'deleted' => 'n'] ) == 0 ) {
             $DB->delete_records('questionnaire_response', ['questionnaireid' => $qid]);
         }
     }

```

All the best,
Michael

**Comment by mchurchward** [comment]
Thanks. This is now fixed - https://github.com/PoetOS/moodle-mod_questionnaire/commit/6bb24d47519c2252647a3e1cd74301358b95af6f
