### ISSUE TITLE
Use question classes for mobile support

### ISSUE THREAD

**Issue by mchurchward** [PoetOS/moodle-mod_questionnaire#158]
Refactor the mobile work so that each question object can provide the needed data for the mobile app, rather than using case/if structures in the questionnaire library code.

**Comment by mchurchward** [comment]
Also... Move the library functions questionnaire_get_mobile_data and questionnaire_save_mobile_data into a class, probably questionnaire.class.php.

**Comment by tigusigalpa** [comment]
Mike, do you need a help?

**Comment by mchurchward** [comment]
@tigusigalpa can you take a look at what I have now? I've moved the get and save mobile data functions from lib.php to the questionnaire class, and I've moved all of the question specific get_mobile_data code to the question classes. I haven't moved the save_mobile_data code yet.
It mostly works, but I can't get a questionnaire will all of the question types defined to actually save the data.
I'm using 3.6 to test. I've attached a backup file of the test questionnaire I'm using (it's an mbz file in a zip file).
[backup-moodle2-activity-153-questionnaire153-20181213-1904-nu.mbz.zip](https://github.com/PoetOS/moodle-mod_questionnaire/files/2677319/backup-moodle2-activity-153-questionnaire153-20181213-1904-nu.mbz.zip)
