### ISSUE TITLE
Report by Group may be broken in 3.5.2

### ISSUE THREAD

**Issue by htm-mickcassell** [PoetOS/moodle-mod_questionnaire#169]
We have a site running Moodle 3.5.3+ (Build: 20181204) along with 3.5.2 (Build - 2018120100) (2018050107) and the issue reported in https://github.com/PoetOS/moodle-mod_questionnaire/issues/162 appears to have re-surfaced?

**Comment by mchurchward** [comment]
Thanks for the report. This has now been fixed in the MOODLE_35_STABLE branch (https://github.com/PoetOS/moodle-mod_questionnaire/commit/1375e4fb9d1dccd6c250167374d6980ef24da6e6) and will be in the release of questionnaire.
