### ISSUE TITLE
Exception - Call to a member function has_choices() on null

### ISSUE THREAD

**Issue by davidpesce** [PoetOS/moodle-mod_questionnaire#172]
When downloading certain responses, I am getting the following error:
`Exception - Call to a member function has_choices() on null`

Full Stack Trace
```
Debug info: 
Error code: generalexceptionmessage

Stack trace:
line 3073 of /mod/questionnaire/questionnaire.class.php: Error thrown
line 485 of /mod/questionnaire/report.php: call to questionnaire->generate_csv()

Output buffer: Notice: Undefined offset: 5144 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3042
Notice: Trying to get property of non-object in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3043
Notice: Undefined offset: 5144 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3044
Notice: Undefined offset: 5144 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3072
```

Environment Info:
- CentOS 7.5, Apache 2.4, MariaDB 10.3, PHP 7.2
- Moodle Moodle 3.5.3+ (Build: 20181128)
- Questionnaire Plugin v3.5.3 (Build - 2018121000)

**Comment by davidpesce** [comment]
Further details with full debug turned on. There are at least a hundred of these printing out.
```
Warning: A non-numeric value encountered in /var/www/moodledir/public/mod/questionnaire/classes/response/rank.php on line 129

Warning: A non-numeric value encountered in /var/www/moodledir/public/mod/questionnaire/classes/response/rank.php on line 129

Warning: A non-numeric value encountered in /var/www/moodledir/public/mod/questionnaire/classes/response/rank.php on line 129

Notice: Undefined offset: 3 in /var/www/moodledir/public/mod/questionnaire/classes/response/rank.php on line 129

```

**Comment by mgancarzdsi** [comment]
@davidpesce , now that I've updated to latest questionnaire mod, it looks like the error message I'm getting is same as yours. Though I don't get an error when downloading CSV. Only when viewing all responses, ie: /mod/questionnaire/report.php?instance=####&action=vall

**Comment by mchurchward** [comment]
I can't replicate this problem. I am using release 3.5.3 (Build - 2018121000). Is it possible it has been fixed with the latest releases? Please verify. If it is still occurring, please post exact steps to replicate including the questionnaire questions.

**Comment by davidpesce** [comment]
I've got a course backup (mbz) with just the questionnaire. How should I get it to you?

**Comment by mchurchward** [comment]
Can you attach it to a comment here?

**Comment by davidpesce** [comment]
I'd rather not. Too many possible other users downloading it. I can send you a dropbox link to the email address on your github profile. Will that work?

**Comment by mchurchward** [comment]
Dropbox will work. You can also try a backup without user data.

**Comment by mchurchward** [comment]
Thanks. Found the problem. Fixed in commit https://github.com/PoetOS/moodle-mod_questionnaire/commit/6a4a53164fa5154736f5599dd84016aa82201a3f

**Comment by davidpesce** [comment]
I added the commit and while I don't get the error anymore, the questionnaires that had the problem never stop loading when I click "View all responses". The other questionnaires still load fine.

**Comment by davidpesce** [comment]
@mchurchward - realized I should @ you so that you get a notification. (Since this is closed).

**Comment by mchurchward** [comment]
@davidpesce do you have the loading issue with the questionnaire you sent me?

**Comment by davidpesce** [comment]
Yeah, my error though. It turns out there were 20K responses. It was just taking a while. I think we're good to go. Thank you!

**Comment by davidpesce** [comment]
@mchurchward - sorry to bug again. The fix only worked on certain questionnaires. I've got three remaining questionnaires that get the same error. I'll send you the dropbox link.

**Comment by mchurchward** [comment]
I checked the backup file with the two questionnaires in it. I cannot replicate the problem with those. The code I changed does handle the problem that was identified. Are you sure you are still using the code changed with the https://github.com/PoetOS/moodle-mod_questionnaire/commit/6a4a53164fa5154736f5599dd84016aa82201a3f commit?

**Comment by davidpesce** [comment]
Yup, I'm still using that code. That being said, I also implemented the backup fix at that same commit. Is it possible that the backup process is removing something of value?

**Comment by mchurchward** [comment]
The fix in the restore operation just sets the incorrect blank values to null. This would only impact you if you restore the backup  and use that.
I restored the backup you provided without the backup fix and with the backup fix. In both cases, I did not receive the errors.

**Comment by davidpesce** [comment]
Which version of PHP/moodle are you testing on? I'm wondering if it's a PHP issue...

**Comment by mchurchward** [comment]
Currently I am testing on Moodle 3.6.2 using PHP 7.0.33 and MariaDB version 5.5.57. But none of that should impact the problem. The problem is that for some of your choice entries in the 'questionnaire_quest_choice' table, the 'value' field contains the empty string when it should be the null value.
The empty string value is what I am getting from your backups.
One other thing we could try, if you are able to make changes to code...
In the 'classes/response/rank.php' file, change line 109 from:
`if (($row->value !== null) && ($row->value !== 'NULL') && ($row->value !== '')) {`
to:
`if (($row->value !== null) && ($row->value !== 'NULL') && (trim($row->value) !== '')) {`
Its possible that your field has blank characters in it that is somehow being transposed to the empty string by the backup process.

**Comment by davidpesce** [comment]
Ahh, good point. I tried that just now and it doesn't change the output. Let me pull up the DB and see what's going on there.

**Comment by davidpesce** [comment]
In mdl_questionnaire_response_rank, I don't see any values (in rankvalue column) other than 0,1,2,3, or 4. Should I be looking in another table?

**Comment by davidpesce** [comment]
Actually, looking at the code, I think you're referring to the mdl_questionnaire_quest_choice table.

Sure enough, I have a bunch of blanks in the value column.

**Comment by mchurchward** [comment]
mdl_questionnaire_response_rank:rankvalue should always have numeric values so that's correct. But that's not the table/field we're worried about. It's the mdl_questionnaire_quest_choice:value column.

**Comment by mchurchward** [comment]
You said: 'Sure enough, I have a bunch of blanks in the value column.'.
Yes. The question is how many blanks. What I am seeing is an empty string (a string with nothing, not even blanks).
What is the exact error message you are getting now?

**Comment by davidpesce** [comment]
I'm still getting the same error. 

I'd say about 80% of the fields are blank. The sampling I've done doesn't even show a blank string in them. They're just blank.

**Comment by mchurchward** [comment]
> I'm still getting the same error.
Can you please post the whole error message again.

**Comment by davidpesce** [comment]
Here's the full error:
```
Exception - Call to a member function has_choices() on null
```
```
Debug info: 
Error code: generalexceptionmessage
```
```
Stack trace:
line 3073 of /mod/questionnaire/questionnaire.class.php: Error thrown
line 485 of /mod/questionnaire/report.php: call to questionnaire->generate_csv()
```
```
Output buffer: 
Notice: Undefined offset: 964 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3042
Notice: Trying to get property of non-object in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3043
Notice: Undefined offset: 964 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3044
Notice: Undefined offset: 964 in /var/www/moodledir/public/mod/questionnaire/questionnaire.class.php on line 3072
```

**Comment by mchurchward** [comment]
Okay. That is not the same error that was fixed, or that I was getting. I was getting the one in https://github.com/PoetOS/moodle-mod_questionnaire/issues/145
I'll see if I can replicate this one.

**Comment by davidpesce** [comment]
Ahh, yea. It's when I go to download the CSV.

**Comment by mchurchward** [comment]
Hmmm... That error is indicating that one of the question id's in the response doesn't exist. Specifically one with the id '964'. Is there a data row in your 'questionnaire_question' table with the field id equal to 964? If there is, is the 'deleted' field set to 'n'?
If its missing, or the field has been set to 'y', then the question that was responded to has been deleted.

**Comment by davidpesce** [comment]
Yup, it's got a "y" for deleted!

**Comment by davidpesce** [comment]
Does it mean I'll have to reactivate that question? Or is there a way to simply restore that within the CSV export?

**Comment by mchurchward** [comment]
That's an interesting question. It hasn't been considered what to do if you are exporting responses that have deleted or missing questions. For now, I'll put a check in that ignores deleted or missing questions.
If you think there could be a need to export responses to deleted questions, create another issue to discuss adding that as an improvement.

**Comment by davidpesce** [comment]
In general, I think that's a good solution (ignore deleted questions).

For this particular client, there is an identical question that is still active. I'm wondering if I can simply change the ID to point to an active question.

**Comment by mchurchward** [comment]
Try this commit - https://github.com/PoetOS/moodle-mod_questionnaire/commit/980e5dfa3bbfb5909b8b076b25ccdd986254acb0
It should fix the problem.

**Comment by davidpesce** [comment]
Yup, it definitely fixes the CSV download error. Unfortunately, it's only returning <1% of the responses in those surveys. 

Do you have a db schema for the plugin? I'm wondering if I can do this on the back-end...

**Comment by davidpesce** [comment]
It looks like they (client) changed the question type from numeric (that's the deleted question) to rate (rank). I don't even think that'll work unless it follows the same rate, right?

**Comment by davidpesce** [comment]
Well, for better or worse, I made the change in the db and it fixed the issued with one of the surveys!

How did you come upon the 964 value? If I can find that same value for the other surveys, I think I'll be all set!

**Comment by mchurchward** [comment]
You should get exactly the same number of responses as you get for the "View all responses". Is this not so?

**Comment by davidpesce** [comment]
Nope, I wasn't getting the same number. For instance, in one I was getting 11 entries in the CSV, but 693 in the "view all responses".

I was able to resolve the issue by updating the mdl_questionnaire_response_text:question_id to the question that wasn't deleted. Since it was a change from numeric to text, it didn't impact the table structure. Everything seems to be working now!

I backed out the change in 980e5df and things still seem OK. I'll have client test and get back to us.

It may be worthwhile to lock the questionnaires once there are entries. That seems to be what other parts of Moodle do.

**Comment by mchurchward** [comment]
Right now, if you delete a question, it tells you how many responses to that question there are and that those responses will be deleted as well. It would not be possible to get into the situation you are in with the current questionnaire. I can only assume this was done with much earlier versions.
I am going to keep the changes that I made as they will prevent the errors you had from occurring in the event there are others out there with messed up responses.

**Comment by davidpesce** [comment]
Ahh, yea. This was definitely an early version of the plugin. 

I think your solution of prompting and then deleting the responses is perfect.

Thanks for all your work on this!
