### ISSUE TITLE
rate scale with No duplicate choices bug

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#176]
When answering rate questions with the No duplicate choices option, if student clicks on the zone to the left or to the right of the radio button, it's possible to have duplicate choices in columns.
See https://moodle.org/mod/forum/discuss.php?d=380415#p1533438

**Comment by mchurchward** [comment]
After reading the forum posts, I'm still not clear on what problem this is causing? Are you saying that the same choice is possible for multiple rows when "no duplicates" is selected? The diagram provided in the forums posts does not show that.

**Comment by mchurchward** [comment]
Okay. I see what you are saying. The javascript that prevents duplicate entries doesn't work when you click outside the button. Clicking the button on a duplicate choice, unchecks the duplicate; clicking the cell does not.
I'll see how to fix that javascript. I think there should also be a check when the submission is made as well, to ensure no duplicate choices.

**Comment by mchurchward** [comment]
Referencing the proposed fix from the mustache file proposed on moodle.org.
/templates/question_rate.mustache:

```
@@ -136,7 +136,7 @@
     <tr class="raterow">
       {{#cols}}
       <td {{#colstyle}}style="{{.}}"{{/colstyle}}{{#colclass}} class="{{.}}"{{/colclass}}{{#coltitle}} title="{{.}}"{{/coltitle}} 
-                       {{#colinput}} onclick="if('{{id}}'.length>0) document.getElementById('{{id}}').checked = true"{{/colinput}}>
+                       {{#colinput}} onclick="if('{{id}}'.length>0) document.getElementById('{{id}}').click()"{{/colinput}}>
         {{#coltext}}{{{.}}}{{/coltext}}
         {{#colhiddentext}}<span class="accesshide">{{{.}}}</span>{{/colhiddentext}}
         {{#colinput}}<input type="radio" name="{{name}}" id="{{id}}" value="{{value}}"{{#checked}} checked="checked"{{/checked}}{{#disabled}} disabled="disabled"{{/disabled}}{{#onclick}} onclick="{{.}}"{{/onclick}}>
```

**Comment by mchurchward** [comment]
Fixed with this commit - https://github.com/PoetOS/moodle-mod_questionnaire/commit/588462f5b73952b20c457cbca8a7485ca25d6e06
