### ISSUE TITLE
For 3.6, remove reference to lib/eventslib.php and its deprecated functions

### ISSUE THREAD

**Issue by lucaboesch** [PoetOS/moodle-mod_questionnaire#178]
See: lib/upgrade.txt

The eventslib.php file has been deleted and its functions have been moved to deprecatedlib.php.

File mod/questionnaire/locallib.php is including lib/eventslib.php

Best,
Luca

**Comment by mchurchward** [comment]
Hi Luca -
That was removed with https://github.com/PoetOS/moodle-mod_questionnaire/commit/20942dddaaf99f403b5047efda113dc538b837be back in November. It was released with 3.5.2.
