### ISSUE TITLE
Parameter missing in error message

### ISSUE THREAD

**Issue by leac** [PoetOS/moodle-mod_questionnaire#182]
As an admin I was in the question edit screen. I then changed my role to Student, and got a "no permission" message. That's understandable, but **the message was missing the action parameter**:

> "Sorry, but you do  not currently have permissions to do that **({$a})**"

I traced the message to[ line 59 in questions.php](https://github.com/PoetOS/moodle-mod_questionnaire/blob/master/questions.php#L59):
```
if (!$questionnaire->capabilities->editquestions) {
    print_error('nopermissions', 'error', 'mod:questionnaire:edit');
}
```
First of all, the message string should be the 4th parameter, not the 3rd. Second of all, that string should be called with `get_string()` and translated.

**But more importantly, maybe the `require_capability()` method would be a better choice?** I tried this and it works:
`require_capability('mod/questionnaire:editquestions', $context);`

I know this is an esoteric error, but it seems relatively easy to fix :)

**Comment by mchurchward** [comment]
Questionnaire is a very old module, and has the "capabilities" loaded into an object property in order to prevent repeated calls to "*_capability" functions. This was done prior to any caching in Moodle. Now that the capabilities are cached, loading these is unnecessary, and the structure should be replaced by calls to require_capability and has_capability.

**Comment by mchurchward** [comment]
The fourth parameter in this case are the extra words ({$a}) that are inserted into the message. In this case, it is the specific capability that is missing. Capabilities are not translated.

**Comment by mchurchward** [comment]
Fixed in commit https://github.com/PoetOS/moodle-mod_questionnaire/commit/d463b525faefc4ca4654220f3c58271b876159b3
