### ISSUE TITLE
Update date question to use HTML5 date selector

### ISSUE THREAD

**Issue by mchurchward** [PoetOS/moodle-mod_questionnaire#183]
HTML5 now has a date selector input form type. Well a very few browsers don't support it (e.g. IE and Safari), the majority do. Update the date question type to use this selector type. Browsers that don't will default back to a standard text input, so validation of the date will still be necessary.
Additionally, input of the date will have to be YYYY-MM-DD regardless of the 'dateformatting' language string.

**Comment by mchurchward** [comment]
This also means that dates older than 1970-01-01 can now be entered.

**Comment by TubsDK** [comment]
It would be nice if the check would follow moodle dateformating instead of the strict YYYY-MM-DD . Eg european style DD-MM-YYYY .

**Comment by mchurchward** [comment]
Well, ideally the date is selected from the date selector, making the format moot.
