### ISSUE TITLE
Question type yes/no doesn't apply attribute to input "no"

### ISSUE THREAD

**Issue by adpe** [PoetOS/moodle-mod_questionnaire#186]
Hello @mchurchward 

When creating a question of this type `Yes/No` and responded with `No` the value is stored in the backend correctly but the view has an error.

The element doesn't have the necessary attribute `checked="checked"`

![image](https://user-images.githubusercontent.com/9467708/54745603-310e2b80-4bca-11e9-958c-1769e5b32d37.png)

Thanks for fix it
Adrian

**Comment by mchurchward** [comment]
Thanks for the report. This has now been fixed in the MOODLE_35_STABLE branch at https://github.com/PoetOS/moodle-mod_questionnaire/commit/c498c86b8435da16d7ab48f319df7b0f10ff05d0 and will be in the next release.
It has also been fixed in the MOODLE_36_STABLE branch, not yet released.

**Comment by GirlieNinja** [comment]
@mchurchward Is it possible this bug was reintroduced? I've downloaded the latest version for 3.5 from moodle.org and I do not see the checked="checked" in the response_yesno.mustache file.

**Comment by mchurchward** [comment]
It was released in `[3.6.1](https://moodle.org/plugins/pluginversion.php?id=19726)`, which works on 3.5.

**Comment by GirlieNinja** [comment]
Can you update that page to say that it will work in 3.5? right now it says "NOTE - The 3.6 releases will only work on Moodle 3.6 and Moodle 3.7. The 3.5 releases will work on Moodle 3.7, 3.6, 3.5, 3.4
and 3.3." and I'm thinking it might be hard for me to get it pushed in to our 3.5 branch if that's the case.

**Comment by logan-reynolds** [comment]
Release 3.6.1 (Build - 2019052400) will _not_ install on Moodle 3.5 due to a requires value of 2018120300 (M3.6 or higher only.)  So users wanting this fix on Moodle 3.5 will need to wait until an M3.5-specific version with this fix is released.

**Comment by mchurchward** [comment]
Yes, I'm sorry. That is correct. You need at least Moodle 3.6 to get this fix.
