### ISSUE TITLE
Deleting a Questionnaire Template

### ISSUE THREAD

**Issue by rlcarbone** [PoetOS/moodle-mod_questionnaire#188]
Hi,
Is it possible to delete a questionnaire template without deleting the questionnaire activity? I know I can change the template to private however, it still appears as a usable template when creating a questionnaire activity and selecting the "Use Template" radio button option under "Content Options." Does a reliable way exist to remove templates without the create of the template removing the activity?

Thank you,

**Comment by mchurchward** [comment]
A questionnaire template is a questionnaire activity. Once it has been deleted, it is not available, and will not show up as a template to use when creating a new one (you will see "Use template  (No template questionnaires.)").
To delete it, you use delete activity in the course.
If you change a template questionnaire to a private questionnaire, it will no longer appear as a template available to be used in creating a new questionnaire.
