### ISSUE TITLE
Getting error member function has_choices() on Null

### ISSUE THREAD

**Issue by 2shediac** [PoetOS/moodle-mod_questionnaire#189]
Call to a member function has_choices() on null

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

line 3204 of /mod/questionnaire/questionnaire.class.php: Error thrown
line 489 of /mod/questionnaire/report.php: call to questionnaire->generate_csv()

This looks like it occurs when there are deleted questions in the survey responses. They are being included there but excluded in n the question list.

**Comment by mchurchward** [comment]
Can you confirm the version of questionnaire you are seeing this with? Something like this was fixed I believe.

**Comment by 2shediac** [comment]
The original issue was sent a while ago https://moodle.org/mod/forum/discuss.php?d=370654.

The version we are seeing it on is 3.2.6 (Build - 2018013100), - actually using it on Totara 11.

Thanks

if you have another version that this is fixed in let me know.

**Comment by mchurchward** [comment]
In release 3.5.4, in response to [issue 172](https://github.com/PoetOS/moodle-mod_questionnaire/issues/172), this issue was fixed.
