### ISSUE TITLE
Tab in "!other" answer is not replaced. 

### ISSUE THREAD

**Issue by papillon326** [PoetOS/moodle-mod_questionnaire#191]
add "preg_replace("/[\r\n\t]/", ' ', $responsetxt1)"

**Comment by mchurchward** [comment]
Can you provide detail on how to replicate and see the problem this fixes? Thanks.

**Comment by papillon326** [comment]
1. Add new questionnaire to course.
2. Create "checkbox" (or "radio") type question including "!other=" selection.
3. Copy text message with tab from text editor.
4. Answer the question and paste text message into "!other=" text field.  
5. Export CSV.

**Comment by mchurchward** [comment]
Fixed in latest MOODLE_37_STABLE
