### ISSUE TITLE
Web service function not available

### ISSUE THREAD

**Issue by loganthomison** [PoetOS/moodle-mod_questionnaire#194]
I'm using the MOBILEa1.0 release and receive an Error The web service is not available when submitting questions. Is there something server side that I need to enable to utilize the new functionality?

**Comment by mchurchward** [comment]
This is under development right now, and will fail more than it will work. I'll make an announcement when it is ready for alpha / beta testing.

**Comment by mchurchward** [comment]
But, to test, make sure your site is 3.5 or higher, and you have "web services for mobile devices" enabled in your site's Mobile settings.
