### ISSUE TITLE
Non-respondents list showing every user on system level.

### ISSUE THREAD

**Issue by doiphode** [PoetOS/moodle-mod_questionnaire#216]
Non-respondents list showing every user on system level who has mod/questionnaire:submit Allowed, even though the users not enrolled on the course. Better would be to show students only who are enrolled on the course.

**Comment by nadavkav** [comment]
We also experience this

**Comment by nadavkav** [comment]
Ok. we found out that one of the Admins changed the _Manager_ role capability _mod/questionnaire:submit_ to _Allowed_, which added all the managers from all the parent categories of that specific course to the list of users that did not submitted the questionnaire. 
We revert it to the default and everything is back to normal :-)

**Comment by mchurchward** [comment]
This has now been fixed in MOODLE_311_STABLE and MOODLE_400_STABLE.
