### ISSUE TITLE
Course restore error

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#231]
Moodle 3.7.2 (Build: 20190909)

Questionnaire 3.7.0 (Build - 2019101700) 2019101701

When restoring a course including a questionnaire, error thrown:

Error reading from database

Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AMD qq.surveyid = '2'' at line 1 SELECT qrr.* FROM mdl_questionnaire_question qq INNER JOIN mdl_questionnaire_response_rank qrr ON qq.id = qrr.question_id WHERE qq.type_id = ? AND qrr.rankvalue >= ? AMD qq.surveyid = ? [array ( 0 => 8, 1 => 0, 2 => 2, )] Error code: dmlreadexception

As reported in the Questionnaire forum here: https://moodle.org/mod/forum/discuss.php?d=392487#p1582258

**Comment by mchurchward** [comment]
Fixed with commit 6b3fa5bfef911f5395afd44498bb5ea0ac777350
