### ISSUE TITLE
Provide the ability for each individual results page to be exported to PDF format.

### ISSUE THREAD

**Issue by mchurchward** [PoetOS/moodle-mod_questionnaire#232]
Look into using 3.7's PDF data format for this.

**Comment by mchurchward** [comment]
The 3.7 PDF format will work for the current download report. For the other reports, renderers for PDF export will need to be created.

**Comment by mchurchward** [comment]
Need to get rate questions working.
Need to prettify the whole thing.

**Comment by mchurchward** [comment]
Will need to revisit this and design something within the PDF output itself. The HTML simply does not translate well to PDF. Enabling an HTML print option for now.

**Comment by timhunt** [comment]
Just to confirm, that is basically what we found. When we wanted good printing for quiz attepts, we focussed on making a HTML page that printed well (including @media print rules). The result is https://github.com/moodleou/moodle-quiz_answersheets.

Then, when we did really want to produce the PDFs for those in bulk, I discovered https://github.com/puppeteer/puppeteer which is a way basically lets you run Chrome in the backround from a NodeJS script. Therefore, you can use Chrome's save-as PDF option to save HTML pages to PDF quite effectively. However, that does require running a separate script outside Moodle to do the Save-as-PDF-ing. It is not nicely integrated.

Just thought that info might be helpful.

**Comment by mchurchward** [comment]
Thanks for the info!
