### ISSUE TITLE
Upgrade fails due to timeout

### ISSUE THREAD

**Issue by aspark21** [PoetOS/moodle-mod_questionnaire#249]
Upgrading from Moodle 3.7.2 to Moodle 3.7.3

and questionnaire from master @ 5509c94f97c672a290db15aac7960b1b7c4a456 (i.e. essentially where MOODLE_36_STABLE is currently at) 

to MOODLE_37_STABLE @ f3b797fa625518abc0c961cb19c87dbfc4a16cb5

Fails with the mod_questionnaire step timing out.

**Comment by mchurchward** [comment]
Can you tell me specifically what version you are upgrading from / to? I'm guessing this might be the same issue reported here - https://moodle.org/mod/forum/discuss.php?d=392877 ?

**Comment by mchurchward** [comment]
I added this 0bb2911945c8067b59447310f5cf6c6e787a3b99 which may fix this? It significantly reduces the amount of memory used.

**Comment by djdevin** [comment]
I don't think it's a memory issue, update 2018110103 takes a really long time (hours).

This is on ~2000 questionnaires, ~30000 questions, ~100000 responses, almost all of them "rate" questions.

**Comment by mchurchward** [comment]
The latest code in MOODLE_37_STABLE has a fix for this. Specifically d2f7c655b1c38e86a3eb159b123c0836c05c894c
