### ISSUE TITLE
Download responses data as text (cvs) format - buffer not empty

### ISSUE THREAD

**Issue by mcardle** [PoetOS/moodle-mod_questionnaire#263]
In MOODLE_36_STABLE branch (and maybe others too) when downloading responses as CSV we sometimes get an exception error in the download_as_dataformat() function since it checks for the buffer length and it is not empty.

We have made a fix by adding

```
// Sometimes the buffer is not empty and this will throw an exception in the download_as_dataformat() function.
ob_end_clean();
```
on line 490 in report.php

I will make a pull request for this issue in a bit.

**Comment by mcardle** [comment]
I should mention, that I we are currently using Moodle 3.6.6+ (Build: 20191016) on that site along with theme_clean (not that I think it matter)

**Comment by mcardle** [comment]
Pull request created

https://github.com/PoetOS/moodle-mod_questionnaire/pull/264

**Comment by mchurchward** [comment]
Left a comment on the pull request. The buffer issue should never happen. Can you provide a test case?
