### ISSUE TITLE
Moodle Filters are not applied to title and subtitle in completepage.php

### ISSUE THREAD

**Issue by glu000** [PoetOS/moodle-mod_questionnaire#272]
In file questionnaiere.class.php, function print_survey_start add call to format_string:

Instead of

`            if (!empty($this->survey->title)) {
                $this->page->add_to_page('title', clean_text($this->survey->title, FORMAT_HTML));
            }
            if (!empty($this->survey->subtitle)) {
                $this->page->add_to_page('subtitle', clean_text($this->survey->subtitle, FORMAT_HTML));
            }
`

it should be

`            if (!empty($this->survey->title)) {
                $this->survey->title=format_string($this->survey->title);
                $this->page->add_to_page('title', clean_text($this->survey->title, FORMAT_HTML));
            }
            if (!empty($this->survey->subtitle)) {
                $this->survey->subtitle=format_string($this->survey->subtitle);
                $this->page->add_to_page('subtitle', clean_text($this->survey->subtitle, FORMAT_HTML));
            }
`

**Comment by mchurchward** [comment]
Fixed in MOODLE_39_STABLE.
