### ISSUE TITLE
Add css class to mobile handler

### ISSUE THREAD

**Issue by nguyenphuctien** [PoetOS/moodle-mod_questionnaire#280]
We want to custom css of questionnair module on the mobile app, but the mobile handler is missing css class.
Could you please add a class call **core-course-module-questionnair-handler** to php file below? https://github.com/PoetOS/moodle-mod_questionnaire/blob/master/db/mobile.php:30
            'questionsview' => [
                'displaydata' => [
                    'icon' => $CFG->wwwroot . '/mod/questionnaire/pix/icon.svg',
                    'class' => 'core-course-module-questionnair-handler',
                ],

Thanks!

**Comment by mchurchward** [comment]
Being handled in PR https://github.com/PoetOS/moodle-mod_questionnaire/pull/281
