### ISSUE TITLE
Null property in course_module_viewed event

### ISSUE THREAD

**Issue by sharpchi** [PoetOS/moodle-mod_questionnaire#291]
I'm getting the following error when creating a new questionnaire:
Notice: Trying to access array offset on value of type null in /var/www/html/moodle38/mod/questionnaire/classes/event/course_module_viewed.php on line 54

I think it's the `$this->other['viewed']` bit. It's never set.
You could probably do away with the function altogether, and let the parent class handle this.
Happy to do a pull request if useful.

**Comment by mchurchward** [comment]
Hmmm. That was added in Moodle 2.7. Do you know if that was ever valid?

**Comment by mchurchward** [comment]
Fix pushed here b8137c0227407149d3f8f01c345548d13474feee.
