### ISSUE TITLE
master branch version is incoherent

### ISSUE THREAD

**Issue by aspark21** [PoetOS/moodle-mod_questionnaire#293]
This upgrade step sets the Plugin version to 2020011505
https://github.com/PoetOS/moodle-mod_questionnaire/commit/b06130af6dcaaacc96c76a877b4487ffa101fd92#diff-5bbd3ccd25214f9956eea7e9f714bc08R27

But for some reason you downgraded the version of the plugin on master branch 
https://github.com/PoetOS/moodle-mod_questionnaire/commit/a3ad4233762cd4248eac34947b1822e37ee8cb41#diff-5bbd3ccd25214f9956eea7e9f714bc08L27

This means after successfully upgrading questionnaire on Moodle 3.9, one is told off for trying to downgrade the plugin's version

**Comment by mchurchward** [comment]
The master branch is not a branch you should be installing. It typically lags behind the current stable branch. I try to update the main version number to the next stable branch when I release a new stable branch, but must have missed it this time. In any case, stick with the latest stable branch, which is currently MOODLE_38_STABLE.

**Comment by mchurchward** [comment]
The master branch is currently in step with the latest MOODLE_39_STABLE branch, but will diverge soon.
