### ISSUE TITLE
Language filter is not supported on the View All Response Page

### ISSUE THREAD

**Issue by gemguardian** [PoetOS/moodle-mod_questionnaire#295]
I noticed that the language filter is not being supported on the View All Response page. 

![image](https://user-images.githubusercontent.com/16559999/85261593-a5d6b200-b46c-11ea-91cf-e70620cec197.png)

![image](https://user-images.githubusercontent.com/16559999/85261692-d4548d00-b46c-11ea-9d27-42df4fdc7971.png)

**Comment by mchurchward** [comment]
Does the language filter work on the main page where you start to complete it?

**Comment by mchurchward** [comment]
Fix added to MOODLE_39_STABLE branch.
