### ISSUE TITLE
Replace deprecated 'download_as_dataformat()' function

### ISSUE THREAD

**Issue by mchurchward** [PoetOS/moodle-mod_questionnaire#296]
download_as_dataformat() is deprecated, please use \core\dataformat::download_data() instead

- line 42 of /lib/dataformatlib.php: call to debugging()
- line 502 of /mod/questionnaire/report.php: call to download_as_dataformat()

**Comment by mchurchward** [comment]
Fixed in MOODLE_39_STABLE branch.

**Comment by jkram** [comment]
I'm curious when this might make its way into the 3.8.3 (Build - 2020062400) (2020011508) version at https://moodle.org/plugins/pluginversions.php?plugin=mod_questionnaire

Sorry if a mis-placed question.

**Comment by mchurchward** [comment]
When the 3.9 release comes out, it will be in there. You can see it in the MOODLE_39_STABLE branch now.
