### ISSUE TITLE
Can set "Close Date" to be before "Open Date"

### ISSUE THREAD

**Issue by rlorenzo** [PoetOS/moodle-mod_questionnaire#300]
We are using 3.9.0 (Build - 2020062300), but noticed this in earlier versions as well.

Under Timing, you can set the "Use Open Date" and "Use Close Dates" to invalid time periods. There isn't an error message given. You can set Open to be after Close and Close before Open.

**Comment by mchurchward** [comment]
Thanks for the report. I will work on fixing this.

**Comment by mchurchward** [comment]
Fixed in 6fd380ceab5d35ec0d0a870543e232fb4a8bc577
