### ISSUE TITLE
 inputs a 0 answer in a numerical survey

### ISSUE THREAD

**Issue by syusanjun** [PoetOS/moodle-mod_questionnaire#301]
If a student inputs a 0 answer in a numerical survey, the answer will not be recorded. 
Respondents are not recorded even after downloading csv.

Moodle Version Moodle3.8.3Moodle3.9
questionnaire
3.8.3 (Build - 2020062400) (2020011508) Moodle 3.8, 3.9

**Comment by mchurchward** [comment]
Thanks. I have replicated the problem and will work on a solution.

**Comment by mchurchward** [comment]
Fixed in commit a93727ab6f48a29a9ea19f8656a9941c769a4641
