### ISSUE TITLE
Deprecated: array_key_exists()

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#312]
Moodle 3.9.2 (Build: 20200914)
DEVELOPER: extra Moodle debug messages for developers
Questionnaire 3.9.0 (Build - 2020062300) 2020062301
_Previewing_ questionnaire throws this error: 
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in \moodle\mod\questionnaire\classes\question\question.php on line 897

**Comment by rezeau** [comment]
Bug still not fixed in version 3.9.1 (Build - 2020111801)

**Comment by mchurchward** [comment]
I don't think that line of code should ever be reached any more. What are the steps you are using to cause that?

**Comment by comete-upn** [comment]
Hello,

We have this warning too using Moodle 3.9.7 and PHP 7.4 when trying to preview a questionnaire.

**Comment by mchurchward** [comment]
> Hello,
> 
> We have this warning too using Moodle 3.9.7 and PHP 7.4 when trying to preview a questionnaire.
> 
> > And we get another warning: **Notice:** Trying to access array offset on value of type null in **mod/questionnaire/classes/question/question.php** on line **975**
> > It occurs when editing a question.

Should be fixed in the latest 3.10.0 release.
