### ISSUE TITLE
lost progress after missing an item

### ISSUE THREAD

**Issue by rschafnitzel** [PoetOS/moodle-mod_questionnaire#313]
Hello,
I've stumbled upon a bug. I would appreciate it, if someone could help me out or fix it. If a participant misses an answer on a scale-question, all of his progress on the whole page is lost and he has to answer anew.

steps to reproduce:
1. create scale-question (may apply to other types of questions, too)
2. ignore entire scale question or miss one item of the question while completing the survey
3. proceed to next page or hand in
4. warning message appears, which indicates to missing answer

Actual result:
All answers provided on the page are gone. Participant has to answer every question anew.

Expected result: 
Provided answers for other questions or individual items of the same question should remain.

Thanks!

**Comment by rezeau** [comment]
Cannot reproduce. _Not a bug_ for me.

**Comment by rschafnitzel** [comment]
Thanks for the answer and your time. It seems, an outdated version of Moodle was causing the issues. My university just updated to 3.9 - all errors are gone now.
Sorry for the inconvenience.
