### ISSUE TITLE
export formats

### ISSUE THREAD

**Issue by rschafnitzel** [PoetOS/moodle-mod_questionnaire#314]
Hello,

i can only export data as .csv. Other formats, which are mentioned in the documentation, are absent. The administrator cannot enable more download options.

Is .csv the only option, i.e. is the documentation outdated?

Thanks!

**Comment by rezeau** [comment]
Using Moodle latest (3.10) and Questionnaire latest (version 2020111100) all export formats work as expected.
This is _not a bug_ for me.
Please _provide more information_ (moodle & questionnaire versions, etc.)

**Comment by rschafnitzel** [comment]
Thanks for the answer and your time. It seems, an outdated version of Moodle was causing the issues. My university just updated to 3.9 - all errors are gone now.
Sorry for the inconvenience.
