### ISSUE TITLE
Preview removes responses when submitted!

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#319]
When Previewing a questionnaire, upon **Submit Preview**, the current responses (ticked radio buttons, checked boxes, etc.) should _not_ be reset. The screenshots show the current buggy defective display of latest Questionnaire version as compared with the correct display of an older version, the oldest I could install on my Moodle 3.10 Test site.
![2020-12-11_18-36-32](https://user-images.githubusercontent.com/503583/101936739-38b50580-3be1-11eb-97f1-5efb1a7e613e.jpg)
![2020-12-11_18-36-48](https://user-images.githubusercontent.com/503583/101936763-410d4080-3be1-11eb-985d-a1e865bb0cf4.jpg)
![2020-12-11_18-37-37](https://user-images.githubusercontent.com/503583/101936776-44083100-3be1-11eb-806a-df3b5186e9a2.jpg)

**Comment by rezeau** [comment]
Easy fix here: https://github.com/PoetOS/moodle-mod_questionnaire/pull/320
Should be applied from the moodle 3.7 version onwards.

**Comment by mchurchward** [comment]
Fixed with pull request #320
