### ISSUE TITLE
Download CSV doesn't download all responses

### ISSUE THREAD

**Issue by adpe** [PoetOS/moodle-mod_questionnaire#351]
HI @mchurchward 

We encountered a problem with a public questionnaire with more than thousands of responses. After writing 80 rows in to the CSV file it is done. Therefore, there are missing a lot of responses in the export.

After debugging it, it works, when I change the line https://github.com/PoetOS/moodle-mod_questionnaire/commit/980e5dfa3bbfb5909b8b076b25ccdd986254acb0#diff-65989a245d5a5ed970062220df367f554447fcef1f6407d411a8d00bde1c2172R3045 to a `continue`.

Greets
Adrian

**Comment by mchurchward** [comment]
Thanks. Your pull request has been merged.
