### ISSUE TITLE
Stored xss

### ISSUE THREAD

**Issue by T0pH4nter0cheK** [PoetOS/moodle-mod_questionnaire#353]
There is a possible security issue with questionnaire.
Details have been moved to a hidden comment until after fix has been released.
Thanks.

**Comment by mchurchward** [comment]
**Moving issue description to hidden comment.**

Hi!
I found ability execute javascript code via student role. Student not trusted user and its input must be filtered.
Steps to reproduce:
1. Create questionnaire
2. Add questions with type `Essay box`
3. Select Response format as `Plain text`
4. Save question and login as student.
5. When you answer on question paste xss payload. For example `<xss onafterscriptexecute=alert(document.cookie)><script>1</script>`
6. At teacher execute javascript when looks at the answers. For example  `http://host/mod/questionnaire/report.php?action=vresp&sid=1&currentgroupid=&rid=1&individualresponse=1`. or `http://host/mod/questionnaire/print.php?qid=1&rid=1&courseid=id&sec=1` (If this is the first answer in the questionnaire )
![Screenshot from 2021-07-28 00-51-28](https://user-images.githubusercontent.com/58399421/127233010-aa5ebbb7-c466-465f-a9ab-a5ef6b649008.png)


Tested on last plugin version downloaded from https://moodle.org/plugins/mod_questionnaire
Thanks!

**Comment by mchurchward** [comment]
Can you test this PR #354 for fixing both existing responses and any new responses? Thanks.

**Comment by mchurchward** [comment]
This issue has been addressed and fixed in the current 3.10.1 release, that supports 3.9 upward.
