### ISSUE TITLE
regression in the text question type display

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#370]
See this questionnaire forum discution: https://moodle.org/mod/forum/discuss.php?d=428875#p1725984
in the questionnaire/classes/question/text.php script this change from version 3.10.0 to version 3.10.1 caused the bug:
@@ -85,7 +85,8 @@ protected function question_survey_display()
version 3.10.0:
$choice->value = (isset($response->answers[$this->id][0]) ? stripslashes($response->answers[$this->id][0]->value) : '');
version 3.10.1
$choice->value = (isset($response->answers[$this->id][0]) ? format_text(stripslashes($response->answers[$this->id][0]->value)) : '');

**Comment by mchurchward** [comment]
Looks like this change was too thorough. This also affects "other" answers for radio and checkboxes.
For  these cases, it looks like "format_text" should not be used. I do believe they should use format_string.

**Comment by mchurchward** [comment]
This has been [fixed here](https://github.com/PoetOS/moodle-mod_questionnaire/commit/70950e03070cacfad9970f5321aa4e66007ccc0b).
