### ISSUE TITLE
[Moodle 3.9.x] [mod_questionnaire 3.9.1] response "rid" is read before it is ever written to

### ISSUE THREAD

**Issue by danowar2k** [PoetOS/moodle-mod_questionnaire#371]
It seems that somewhere a rid of a response is read before it is ever written to. Looks like the reading function doesn't know if the response is from the database or not...? (But I don't know what "rid" is exactly, so...)

How to provoke:

* Create a new questionnaire, give it a name, "Save and Display"
* Click on "Add Questions"
* Select "Rate (Scale 1..5)" and "Add select question type"
* Enter a question text and possible answers:

```
angry
calm
hungry
```

* "Save changes"
* Click on "Preview" tab
* Select a value in each line
* Click "Submit Preview"

Output contains:

```
Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/response/response.php on line 116

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/response/response.php on line 116

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69

Notice: Undefined property: stdClass::$rid in /var/htdocs/moodle/mod/questionnaire/classes/responsetype/rank.php on line 69
```

Questionnaire settings dump:

```
plugin;name;value
"questionnaire";"allowemailreporting";"0"
"questionnaire";"downloadoptions";"response,submitted,institution,department,course,group,id,fullname,username"
"questionnaire";"maxsections";"10"
"questionnaire";"usergraph";"1"
```

**Comment by danowar2k** [comment]
Oh there is a second line in there...I'll do a patch for that one, too.

**Comment by danowar2k** [comment]
I'll look into it...

**Comment by danowar2k** [comment]
I just tested with Moodle 3.11.7 and Questionnaire 3.10.1. I don't get the notices there. I'll compare the two versions...

**Comment by danowar2k** [comment]
https://github.com/PoetOS/moodle-mod_questionnaire/compare/3.9.1...3.10.1#diff-65989a245d5a5ed970062220df367f554447fcef1f6407d411a8d00bde1c2172R1476-R1477

I'll bet this fixed the issue, commit here: https://github.com/PoetOS/moodle-mod_questionnaire/commit/d754337de53285b412b5add1cf79206ce0cc30db

I guess we can close this then?

**Comment by mchurchward** [comment]
Thanks. Closing. I'll close the PR's as well.
