### ISSUE TITLE
Failing Behat tests in Moodle 4.0

### ISSUE THREAD

**Issue by dragos5436** [PoetOS/moodle-mod_questionnaire#402]
Hi,

There are a few Behat tests failing for this plugin:

1. /var/www/html/mod/questionnaire/tests/behat/view_questionnaire.feature:36
   Feature: Questionnaires can be public, private or template
   Scenario: Add a questionnaire from a public questionnaire
```
And I follow "Questionnaire from public": The "(//html/.//a
[./@href][((./@id = 'Questionnaire from public' or contains(normalize-space(string(.)), 'Questionnaire from public') or contains(./@title, 'Questionnaire from public') or contains(./@rel, 'Questionnaire from public')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or self::img) and (contains(./@alt, 'Questionnaire from public') or contains(./@title, 'Questionnaire from public'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Questionnaire from public' or contains(./@value, 'Questionnaire from public')) or contains(./@title, 'Questionnaire from public') or contains(normalize-space(string(.)), 'Questionnaire from public'))])[1]" xpath node is not visible and it should be visible (Behat\Mink\Exception\ExpectationException)
```

2. /var/www/html/mod/questionnaire/tests/behat/multiple_dependency_question.feature:97
   Feature: Questions can be defined to be dependent on answers to previous questions
   Scenario: Student should only be asked questions on school if they have answered yes to question 1.
```
And I follow "Preview": The "(//html/.//a
[./@href][((./@id = 'Preview' or contains(normalize-space(string(.)), 'Preview') or contains(./@title, 'Preview') or contains(./@rel, 'Preview')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or self::img) and (contains(./@alt, 'Preview') or contains(./@title, 'Preview'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Preview' or contains(./@value, 'Preview')) or contains(./@title, 'Preview') or contains(normalize-space(string(.)), 'Preview'))])[1]" xpath node is not visible and it should be visible (Behat\Mink\Exception\ExpectationException)
```

3. /var/www/html/mod/questionnaire/tests/behat/public_questionnaire_teacher.feature:83
   Feature: Public questionnaires gather all instance responses in one master course, but not in the instance courses.
   Scenario: Teacher should not see responses for a questionnaire using a public instance
```
And I press "Submit questionnaire": Javascript code and/or AJAX requests are not ready after 10 seconds. There is a Javascript error or the code is extremely slow (core/first). If you are using a slow machine, consider setting $CFG->behat_increasetimeout. (Exception)
```

MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by mchurchward** [comment]
Not sure which branch of questionnaire you are using. The [latest MOODLE_311_STABLE branch](https://github.com/PoetOS/moodle-mod_questionnaire/tree/MOODLE_311_STABLE) is the one that is currently working with Moodle 4, and it is [passing all Behat tests](https://github.com/PoetOS/moodle-mod_questionnaire/runs/6099614714?check_suite_focus=true).

**Comment by mchurchward** [comment]
All Behat tests are passing in the MOODLE_400_STABLE branch.
