### ISSUE TITLE
Conditional Branches, Rating scales and Required questions

### ISSUE THREAD

**Issue by rezeau** [PoetOS/moodle-mod_questionnaire#415]
In a 'branching questionnaire', rating scale questions set as 'required', can be be skipped! This is a bug.
See https://moodle.org/mod/forum/discuss.php?d=437073#p1759040

**Comment by danowar2k** [comment]
@mchurchward Could you please verify if this fix is correct without side effects? We'd then incorporate it into our version until we switch to a fixed questionnaire version...

**Comment by mchurchward** [comment]
This has been fixed as above.
