### ISSUE TITLE
Error when deleting question in survey with dependencies

### ISSUE THREAD

**Issue by Laur0r** [PoetOS/moodle-mod_questionnaire#427]
When deleting a question in a survey that has dependent questions, the following error message is displayed: `count(): Argument #1 ($value) must be of type Countable|array, stdClass given.`

This stems from line 190 in questions.php where the argument of count() `$haschildren` is a class and not an array. Instead of using count(), an alternative would be to use empty for the check in line 190.
![Questionnaire_error](https://user-images.githubusercontent.com/35337130/193813530-be6f004a-380b-4098-8a45-90e972182f5c.png)

**Comment by mchurchward** [comment]
I believe this is fixed in the above commit.
