### ISSUE TITLE
Moodle 4.0 icon 

### ISSUE THREAD

**Issue by TubsDK** [PoetOS/moodle-mod_questionnaire#435]
I have create a monoversion of the icon. 

@mchurchward  Could you please upload that to the /pix/ folder in preparation of a 4.0 launch? 

![monoicon](https://user-images.githubusercontent.com/8876269/198987779-23ad016e-0f1e-4cbc-9304-df31b644d28f.svg)

**Comment by lucaboesch** [comment]
There's already one in https://github.com/PoetOS/moodle-mod_questionnaire/pull/408, @TubsDK

**Comment by TubsDK** [comment]
@lucaboesch  Thanks  - I tried searching for a logo but could not find it.

**Comment by mchurchward** [comment]
Closed with the above fix.
