### ISSUE TITLE
strange branch names in github

### ISSUE THREAD

**Issue by danmarsden** [PoetOS/moodle-mod_questionnaire#444]
you have a "main" branch which is set to the default branch name but you have a MOODLE_400_STABLE and MOODLE_311_STABLE branches which appear to have "newer" code than the "main" branch does?

maybe you should set the default branch to MOODLE_400_STABLE and delete the "main" branch? - or maybe add some detail to the readme file about what that "main" branch is actually for?

thanks!

**Comment by mchurchward** [comment]
Hi Dan. I don't use the main branch. It is typically the next unreleased version. But yes, I could use some documentation.
Generally, code is kept up to date in the latest Moodle release branch(es), which is currently MOODLE_400_STABLE (unreleased at the moment), and MOODLE_311_STABLE.

**Comment by mchurchward** [comment]
That said, I have changed the default to the current working branch. Thanks.

**Comment by danmarsden** [comment]
cool thanks! - having the default branch set to MOODLE_400_STABLE will help a lot to avoid confusion :-)

FYI if it's useful to know how we do it....  we delete the "main" branch completely in lots of our plugins - usually our latest branch will be named using the lowest supported version for that branch eg auth_saml2 has a latest branch name of MOODLE_39_STABLE - because that branch will work in Moodle 3.9 -> 4.1 - if we have to create a new branch to support a new release (eg Moodle 4.1) we create a new branch to cover that release and higher so we might have
MOODLE_39_STABLE (supports 3.9 -> 4.0)
MOODLE_401_STABLE (supports 4.1 and higher)

That way people can use git submodules/subplugins to add our plugins and the branch name doesn't change unless it has to support a new version.

**Comment by mchurchward** [comment]
Other than deleting the main branch, that is how I do it too. I never considered deleting the main branch. Hmm....
