### ISSUE TITLE
TinyMCE fails to load in Questionnaire with Essay question type.

### ISSUE THREAD

**Issue by Syxton** [PoetOS/moodle-mod_questionnaire#50]
TinyMCE does not load properly.  Student's can't add images.

**Comment by cosmikdust** [comment]
is this issue still around? we are running 2.8.2 (Build - 2015031901) of the plugin, wondering if it would be worth upgrading.

**Comment by mchurchward** [comment]
Using 3.2, I just set my preferred editor to TinyMCE, and it appears to work fine. So does Atto.

**Comment by cosmikdust** [comment]
Arghh, any idea why the students can't add images via the tinyMCE module? i mean there is an exact same essay box in Quiz plugin where they can do so (after enabling html editor with file picker in settings).

**Comment by mchurchward** [comment]
There's a lot of work to implement that. The code needs to use file areas for each response. Then backup and restore has to be modified to handle that. Also, the export to CSV function needs to be able to do something with that. Its just not as straightforward as it seems.

**Comment by mchurchward** [comment]
See https://tracker.moodle.org/browse/CONTRIB-6607
