### ISSUE TITLE
Site managers are included in the list of non-respondants

### ISSUE THREAD

**Issue by Syxton** [PoetOS/moodle-mod_questionnaire#58]

**Comment by mchurchward** [comment]
Is this the same issue that is described here - https://tracker.moodle.org/browse/CONTRIB-5429 ?

**Comment by Syxton** [comment]
yep

**Comment by Syxton** [comment]
I have a pull request that fixes this...just an fyi
https://github.com/remotelearner/moodle-mod_questionnaire/pull/59

**Comment by mchurchward** [comment]
I'm not sure I agree with that pull request. The current code gets all of the users who can submit the questionnaire. Why would that not be correct?
Using the "get_enrolled_users" could include users who are enrolled in the course, but have veeb specifically denied  the capability to submit a questionnaire, couldn't it?

**Comment by Syxton** [comment]
ok, so maybe the better option would be to check for both.  Because currently site level managers are showing up in the list.  And though they do have the ability to take the questionnaire, it is unlikely that they want to get an email to take the questionnaire.  And there is no way to remove them from that list for anonymous questionnaires.

**Comment by Syxton** [comment]
Actually, now that I look at the code, it looks like it is already getting only enrolled users with the capability.

**Comment by Syxton** [comment]
https://docs.moodle.org/dev/Enrolment_API#get_enrolled_users.28.29

**Comment by mchurchward** [comment]
Okay. Then I think to prevent a functional regression problem, we would need to allow for both cases. For this case, maybe a check box that allows you to send to all users who can take a questionnaire (as it is now), or only those that are also enrolled in the course.

**Comment by mchurchward** [comment]
See https://tracker.moodle.org/browse/CONTRIB-5429
