### ISSUE TITLE
Changing answers other questions depend on is not checked

### ISSUE THREAD

**Issue by kyro46** [PoetOS/moodle-mod_questionnaire#79]
Answers of parent questions can be edited and changes are not checked whether they break some dependend behaviour.

Changing the answers for a parent question can lead to missing or wrong references in the corresponding child questions.

Tested with MOODLE_32_STABLE.

**Comment by mchurchward** [comment]
Can you describe, step by step, where you see the problem?
I created a radio button question with three options: "one", "two" and "three". I then created three child questions, each dependent on one of the three answers. I then edited the parent, and changed option "three" to "four". The child question that was dependent on "three" was now dependent on "four". This seems correct.
Deleting a choice does create a question with a dependency that cannot be met. But that dependency can be removed from the question that has it.
What behavior are you expecting?

**Comment by kyro46** [comment]
As a user, I would expect the questionnaire to prevent me from making errors. A user doesn't know about the handling of IDs. Adding an answer in between existing answers should not result in a different dependend answer for a child question, just because the IDs incremented in the background. Deleting an answer in between should not break a dependency on the last answer, which ID is now decremented.

I think, before saving the changed answers, the user should get a modal to inform about the impact of the changes. This would make it consistent with the behaviour, when a question with children is going to be deleted.

An alternative would be, to replace the textbox for answers with a static element, showing the uneditable answers, once a child has been set - this would be consistent with the behaviour of the dependency input.
(But as for the dependencies, I would consider this too restricting.)

Please also check your mail @ poetgroup, for a different matter in a spare minute.

**Comment by kyro46** [comment]
An example for the use case "Inserting answers in between" would be:

===
Question 1: Radio
Answer-1
Answer-2
Answer-4

Question 2
--> Depends on "Radio->Answer-4"

Now I notice "Answer-3" is missing in question 1. I add it, of course in nice alignment with the other answers: Between "Answer-2" and "Answer-4".

While saving the answers, the plugin checks whether the lines are equal to the existing records in the DB. On line 3 it recognizes a change and overwrites the entry in the database, formerly containing "Answer-4" with "Answer-3". The "new" line "Answer-4" gets a new entry in the DB with a new ID.

Question 2 still references the old DB-ID "Answer-4" had in the past. So it now depends on "Answer-3" which took the corresponding place at this ID.
===

It's not mentioned to the user the flow of the questionnaire just changed. The user can only check for the value, not for the ID and has to look for missing (deleting in between) or changed answers (inserting new answers) without any hint from memory. 

So I would be in favour of the modal, stating the impact on the existing flow in the questionnaire and maybe highlighting questions in the questionnaire_form, which have a broken dependency.

**Comment by mchurchward** [comment]
Thanks for the example. I understand your point now.
I think the way it is is rooted in history. The actual 'id' of the choice was never that important until the conditional questions got added. And changing choices after a questionnaire was started was always discouraged as this changed the results.
 But, changing a choice while editing a questionnaire that has conditional questions should be allowed and should be dealt with.
I feel that choices "should" have their own editing function. So it is obvious when a choice's content is changed, vs. adding a new choice. But that would require a lot of changes, and still brings its own problems.
I agree that the easiest and quickest path would be to provide an informational dialogue, informing the editor of the impacts of the change. Ideally, some form of visual flow editor would be good.
Do you have any code you could provide for the simple solution? If not, I'll add it to the pile.

**Comment by mchurchward** [comment]
I'm going to close this issue for now. Choices will need to be reworked and restructured in order to improve these issues.
