### ISSUE TITLE
Feature request: export as xlsx file

### ISSUE THREAD

**Issue by Jarvil** [PoetOS/moodle-mod_questionnaire#81]
Hello,

I would like to see an feature in Questionnare that lets you export/download answers in .xlxs-format, at the moment you can only export .csv file

**Comment by mchurchward** [comment]
I think [CONTRIB-6982](https://tracker.moodle.org/browse/CONTRIB-6982) would provide this.

**Comment by sharpchi** [comment]
Just thought I'd mention that I've put up a test patch on the tracker item. I'd appreciate it if someone tried it out. Happy Christmas

**Comment by mchurchward** [comment]
Thanks. I'll take a look soon.
