### ISSUE TITLE
Adding entry to Dropdown Box question type once some answers have been made buggers up data

### ISSUE THREAD

**Issue by aspark21** [PoetOS/moodle-mod_questionnaire#88]
Moodle 3.0 / Questionnaire 3.0.0 (Build - 2015102800) / Database: MySQL

Question type: Dropdown Box

If, for example a teacher defines a list of students in alphabetical order in the Dropdown box for tutors to select when filling out a questionnaire. Assuming that some students will come and go, if they add new students in that list alphabetically it will screw up all prior submissions because questionnaire stores the value for the position in the dropdown rather than the actual value.

Sure, we can add additions at the bottom of the list and not remove withdrawn students to prevent this from occurring but since the list is in alphabetical order, having randomly some students at the bottom not in alphabetical order is confusing the users filling out the questionnaire.

**Comment by mchurchward** [comment]
Please see my answer posted at https://moodle.org/mod/forum/discuss.php?d=353269

Here is the text for reference:

> This is a know issue with questionnaire. Care should always be taken when modifying the questions of questionnaires that have already been completed by some users. When it was developed, it was assumed that questions would remain mostly static, so that response reports made sense.
> 
> The problem with changing choices in a drop down (for example), is there is no easy way to determine if a change is being made to the text of an existing choice, if a choice is being removed, or if a choice is being added. The code assumes position is important, and assumes that if the text changed for an existing position, then that choice's text changed. If the list gets shorter, choices are deleted from the end of the list. If the list gets longer, choices are added to the end of the list.
> 
> What needs to happen is that there needs to be a more extensive choice editor, so that selections can be made from defined choices. It is not a small change.

**Comment by aspark21** [comment]
Hi Mike,
Fair enough.

With the current approach, could there simply be a "Display in alphabetical order" tick box so that even if more things are added to the list at the bottom to preserve data integrity they all appear naturally in alphabetical order in the dropdown for the person filling out the questionnaire?

**Comment by mchurchward** [comment]
That would certainly be easier. Although it would be better to have a more robust choice editor/selector.
