### ISSUE TITLE
Export of csv file with filename *.txt

### ISSUE THREAD

**Issue by tobiasreischmann** [PoetOS/moodle-mod_questionnaire#96]
Hey,
I just wondered, why the export of the report as csv-file uses ".txt" as file extension. It confused one of our users. In the code there is the comment:
        // SEP. 2007 JR changed file extension to *.txt for non-English Excel users' sake
Since it is 10 years old, I wonder if this comment is this still relevant?
Otherwise, could you change the extension to csv at https://github.com/remotelearner/moodle-mod_questionnaire/blob/master/report.php#L494
Cheers,
Tobias

**Comment by mchurchward** [comment]
The correct thing (I believe) would be to rewrite this feature to use the Moodle Data format API introduced in 3.1.
I created [CONTRIB-6982](https://tracker.moodle.org/browse/CONTRIB-6982) for this.

**Comment by mchurchward** [comment]
This has been dealt with in the latest commit and forthcoming release.
