### ISSUE TITLE
Adding more clickable/tapable space on rate/scale questions

### ISSUE THREAD

**Issue by eglescout** [PoetOS/moodle-mod_questionnaire#99]
This is a 'nice-to-have' request. The following CSS allows the most of the table cell containing the radio button to be clickable.

`.qn-answer td input[type="radio"] { width:100%;}`

I guess the the CSS rule at ~line 286 in **styles.css** could be modified to
`.qn-answer input[type="radio"],
.qn-answer input[type="checkbox"] {
    width:100%;
}`
I also removed the `margin-right: 3px; `  because it no longer seems necessary at least with the themes that I've used. Thanks!

**Comment by mchurchward** [comment]
This has been dealt with in the latest commit and forthcoming release.
